spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: false

cors:
  front-end: ${CORS_FRONT_END:http://localhost:5173}

server:
  error:
    include-stacktrace: never